### ISSUE TITLE
Whids Stopping Logging

### ISSUE THREAD

**Issue by badboycxcc** [0xrawsec/whids#125]
Whids Stopping Logging
Only log from July 31st to August 1st, today is August 4th

os: windows 11

![image](https://user-images.githubusercontent.com/72059221/182739694-ac691c17-1842-482d-9809-e004f4526077.png)

**Comment by badboycxcc** [comment]
Whids log

```
2022/08/01 21:18:32 INFO - Number of rules loaded in engine: 132
2022/08/01 21:18:32 INFO - Update routine running: false
2022/08/01 21:18:32 INFO - Dump forwarding routine running: false
2022/08/01 21:18:32 INFO - Command runner routine running: false
2022/08/01 21:18:32 INFO - Sysmon archived files cleanup routine running: true
2022/08/01 21:18:32 INFO - Starting routine to cleanup Sysmon archived files
2022/08/01 21:18:32 INFO - Starting archive cleanup loop for directory: C:\Sysmon\
2022/08/01 21:18:33 ERROR - Failed to subscribe to channel "Microsoft-Windows-Windows Defender/Operational": The specified channel could not be found.
```

**Comment by qjerome** [comment]
Hey @badboycxcc,

Which version are you using ?
From the logs I guess you are using the latest stable release, could you please confirm ?

**Comment by badboycxcc** [comment]
> 嘿@badboycxcc,
> 
> 您使用的是哪个版本？ 从日志中我猜你正在使用最新的稳定版本，你能确认一下吗？

V1.7.0 .I use this version

**Comment by qjerome** [comment]
Thank you for your feedback.
Can you please try to use the latest beta release, which is more stable than latest stable release >< !
Please don't forget to tell me whether you still get the issue with the latest beta release.

**Comment by badboycxcc** [comment]
ok

qjerome ***@***.***> 于 2022年8月5日周五 上午3:50写道：
