### ISSUE TITLE
service protect just like systemd in linux？

### ISSUE THREAD

**Issue by hz-kelpie** [0xrawsec/whids#128]
does whids have any way to restart self when its broken? 
Im windows devlop beginners, guess win has sth like systemd in linux?

**Comment by qjerome** [comment]
hey @hz-kelpie,

Yes you can do that. It is managed by Windows service manager.
You have two ways to do this, via GUI or via command line.
Graphical way using Services.msc -> Find the service you want to configure (double click) -> Look at the options in "Recovery" Thumbnail
Via command line using `sc.exe failure /?` (you can configure the same settings available in the GUI)

**Comment by hz-kelpie** [comment]
thx !
