### ISSUE TITLE
Benchmark and performance

### ISSUE THREAD

**Issue by michaelhidalgo** [0xrawsec/whids#4]
Hi there, great tool. I was wondering if you have run some sort of benchmarks or performance testing on workstations upon running a threat emulation like Caldera or even Cobalt Strike not only to measure the detection rate but to measure performance (aka CPU and Memory).

Thanks.

**Comment by qjerome** [comment]
Hi Michael,

I did some detections with Caldera but I did not publish the results. Concerning performances I did some quick benchmarks but nothing structured with well defined testing scenarios. If you want to, feel free to make benchmarks (for both detections and performances) and publish your testing scenarios and data.

To test detection rate this can be done using Gene https://github.com/0xrawsec/gene on offline data. Though if you want to test the full range of features like file and memory dumps, events forwarding and so on, your only option is to install WHIDS in your lab.

It would be great if you would like to collaborate on this topic and share your results with the community.

Cheers,

**Comment by michaelhidalgo** [comment]
Thanks for your reply @qjerome , yeah that makes sense. I also learned (I'm a go newbie), that on top of go testing there is a way for doing benchmarks (more about it later on a blog post I will write). But anyway, I will do this benchmark when having some research cycles.
