### ISSUE TITLE
Configuration to have alerts output in json so its easier to read and parse

### ISSUE THREAD

**Issue by michaelhidalgo** [0xrawsec/whids#6]
For standalone installations (aka those that do not use a manager), it would be good to have a config option to generate the alerts output in JSON, with a log rotation of a configurable value (maybe with a default value of 24 hours), so upon 24 hours the log is rotated and the old alerts are gzipped.

There are good reasons for doing that but a potential one is to be able to read those alerts and ship them via Filebeat (https://www.elastic.co/products/beats/filebeat) and send it to a remote location.

**Comment by qjerome** [comment]
By default the alerts are logged as JSON but GZIP compressed. Would it work with filebeat or it cannot handle such a format?
For the log rotation, it is currently based on file size rather than time, is this an issue?

**Comment by michaelhidalgo** [comment]
Hey @qjerome , as per https://github.com/elastic/beats/issues/637, i seems like filebeat is still not able to read gzip files. Maybe it would be good to keep the JSON plain for 24 hours and then rotate it and zip the old one, leaving might bet just 7 (or less) zip files in the directory (so the folder does not grow).

This allow to any other tooling like filebeat read the JSON file directly almost in realtime.

**Comment by qjerome** [comment]
Good idea, I will see how to implement this.

**Comment by michaelhidalgo** [comment]
I'm putting my head around go programming language, but in the meantime, I was code reviewing how beats (filebeat, auditbeat) actually rotates a file and found this file that could be used as a guidance maybe https://github.com/elastic/beats/blob/c4d580eefe52043a02b7961228f0687b7a491d07/libbeat/common/file/rotator.go

**Comment by michaelhidalgo** [comment]
There is also a package called dailyrotate https://github.com/kjk/dailyrotate that could also help.

**Comment by qjerome** [comment]
Hi Michael, thanks for your input. I implemented my own version in my utility library since it is not a big deal to implement. I am considering pushing a beta release but I would need some help to test with filebeat, do you think you could help me with this?

**Comment by michaelhidalgo** [comment]
Hi @qjerome . Sure thing, if you can publish a beta release for that we will give an exhaustive tests. Let me know the link to downloaded.

Thanks!

**Comment by michaelhidalgo** [comment]
@qjerome I will allocate some time this week to do some testing if you could provide that beta.

**Comment by qjerome** [comment]
@michaelhidalgo thanks a lot, I will try to push the release this evening (watch out the release page if you want to be aware asap), anyway I will drop you a message.

**Comment by qjerome** [comment]
@michaelhidalgo beta release has been uploaded, please let me know if what has been implemented fits with your use case

**Comment by michaelhidalgo** [comment]
Great stuff @qjerome , we will be doing some tests and I will sharing the results here. 

Thanks

**Comment by qjerome** [comment]
Thank you @michaelhidalgo and al. (because you always say we :))

**Comment by michaelhidalgo** [comment]
Hey @qjerome , I noticed that the config file has a section to be able to setup the rotation interval, but that section is inside the configuration for the forwarder.

Does this setting apply also if you are running it standalone. I also noticed that two alerts files are created for the same day with the format alerts.1557977451 

I wonder if it is better, for the log rotation interval, to have just a single file alerts.json. After 24h, a backup is created and a new alerts.json is created for tracking the activity of the day.

**Comment by qjerome** [comment]
Hey @michaelhidalgo, thank you for your first feedback.

Yes the logging settings are under the forwarder. This is not to create two different configuration while only one is needed. The idea is that a standalone instance is one with a local forwarder (controlled by local flag in forwarder configuration). When the forwarder is not local, it is supposed to send the logs and remotely and the log files are used to queue the alerts waiting a possible connection to the manager.

Theoretically, only one alerts.XXXXX file should be there ... It is worth noting that a new file is generated at every rotation-interval, but the old logfile should then be compressed to a gzip file. Basically XXXXX is the Epoch time in seconds at which the file is created. If you have two files being written at the same time, the only way (I can think of) this can happen is if you started two WHIDS instances.

**Comment by michaelhidalgo** [comment]
Thanks for your feedback @qjerome, that makes sense. It would be possible to keep the name of the alerts shorter? aka with the epoch time? This is not a major issue but just to keep uniformity with other platforms where the rotation works by just leaving one fine name alerts.json.

I will doublecheck why two files were created. Also can we put a control in place to make sure a single instance is running at the time?

**Comment by qjerome** [comment]
Will try to address this in the latest release.
I will first solve the log file issue (rather quickly I guess).
Then I will try to make WHIDS run as a true Windows service (which will me take more time since I have never done it)
Do you still want to test those two features?

**Comment by michaelhidalgo** [comment]
Having WHIDS running as a windows service will be an asset. For the record, Winlogbeat uses a Powershell script to actually register the service:

`// Delete and stop the service if it already exists.

if (Get-Service winlogbeat -ErrorAction SilentlyContinue) {

  $service = Get-WmiObject -Class Win32_Service -Filter "name='winlogbeat'"

  $service.StopService()

  Start-Sleep -s 1

  $service.delete()

}

 

$workdir = Split-Path $MyInvocation.MyCommand.Path

 

 // the new service.

New-Service -name winlogbeat `

  -displayName Winlogbeat `

  -binaryPathName "`"$workdir\winlogbeat.exe`" -c `"$workdir\winlogbeat.yml`" -path.home `"$workdir`" -path.data `"C:\ProgramData\winlogbeat`" -path.logs `"C:\ProgramData\winlogbeat\logs`""`

**Comment by qjerome** [comment]
Thanks for the input, I will try to work on this during this week

**Comment by qjerome** [comment]
Hi @michaelhidalgo, I created a new release with the changes discussed, implemented:
- Having a more standard log file format (I implemented the same way Linux archives logs)
- Having Whids in a Windows service instead of a scheduled task
Please check it out and give me your feedback, any comment is welcome

**Comment by qjerome** [comment]
Hi @michaelhidalgo, I pushed a new beta release.
Please let me know as soon as you have tested it.
Thanks

**Comment by michaelhidalgo** [comment]
Great stuff! I will keep you posted!.

**Comment by qjerome** [comment]
Hi @michaelhidalgo, did you have the time to test this?
If I have no feedback from you before the next release I will close the issue since I think I did a correct implementation.
Cheers,
